print(" ")
print("Calculator: Addition")
print(" ")
number1 = float(input("Please enter the first number: "))
number2 = float(input("Please enter the second number: "))
print(" ")
print("Answer:")
answer = number1 + number2
print (number1, "+", number2, "=", answer)
print(" ")