varname = input("Please enter the varname:")
var2 = varname.__len__()
print("=======================================================")
print("This is the len function which calculates string length")
print("The length of the varname string is: ", + var2)
print("=======================================================")
var3 = varname.casefold()
print("This casefold function should force the varname into lowercase")
print("If this isn't lower case something went wrong ","[", var3, "]")
print("=======================================================")
var3 = varname.endswith('meme')
print("This endswith function checks if your varname ends in 'meme'?")
print(var3)
print("=======================================================")